"""Add file_hash file_size file_type to resume

Revision ID: f3c1df3c9181
Revises: bd37dabbd027
Create Date: 2026-08-05 23:34:14.014645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c1df3c9181'
down_revision: Union[str, Sequence[str], None] = 'bd37dabbd027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('resume', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('resume', sa.Column('file_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_resume_file_hash'), 'resume', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_file_hash'), table_name='resume')
    op.drop_column('resume', 'file_type')
    op.drop_column('resume', 'file_size')
    op.drop_column('resume', 'file_hash')
    # ### end Alembic commands ###
